### ISSUE TITLE
検索をモーダルなしで実行したい

### ISSUE THREAD

**Issue by noppefoxwolf** [crane-hiromu/PadOSDC_Japan_App#11]
タイムラインの画面をsearchableにして検索したい。
（ただ全日の検索がしたいのに、タブ内で検索するのは少し気持ち悪いので見せ方を考えたい）

**Comment by crane-hiromu** [comment]
モーダルのアニメーションをオフにすれば、それっぽい感じになりますかね🤔

**Comment by noppefoxwolf** [comment]
なるべくSwiftUIのお作法に乗った上で実現したいです
Developerアプリのように１つのListに全日分表示するUIに変えてしまうのはアリかもしれないです

**Comment by crane-hiromu** [comment]
なるほど、、、

> １つのListに全日分表示するUIに変えてしまう

これも考えたのですが、いろいろ考えて今の形にしたので、ちょっとデザインが大きく変わっちゃうので、一旦保留にしたいですね🤔
