### ISSUE TITLE
Contributeしやすくしたい

### ISSUE THREAD

**Issue by noppefoxwolf** [crane-hiromu/PadOSDC_Japan_App#16]
現状.swiftpmの中身がコミットされているので、cloneしてそのまま動かすことが出来ない。
Contribute Guideに.swiftpmを付けてcloneする方法を記載するか、.swiftpmごとリポジトリに置きたい

**Comment by crane-hiromu** [comment]
Playgorundsで開発していると、どうしてもこうなっちゃうのですよね....

> Contribute Guideに.swiftpmを付けてcloneする方法を記載する

これは良さそうですね！（というかナイスアイデアですね！）

**Comment by noppefoxwolf** [comment]
@crane-hiromu 

> Playgorundsで開発していると、どうしてもこうなっちゃうのですよね....

こんな感じでswiftpm配置出来ないですかね？
https://github.com/noppefoxwolf/DebugMenu

**Comment by crane-hiromu** [comment]
Playgroundだとディレクトリが以下のようになっていて

<img src="https://user-images.githubusercontent.com/24838521/184812380-08eb82d9-5ae2-47a2-b6e9-8bfa67e85a77.png" width=500>

↓

<img src="https://user-images.githubusercontent.com/24838521/184812387-ab120ca9-a61e-4b5f-b850-ba64bcadf4b2.png" width=500>

１階層挟むのが無理そうな気がするんですよね🤔

**Comment by noppefoxwolf** [comment]
なるほど、Xcodeで開発してたので気がつきませんでした…w
そしたらREADMEに

```
git clone https://github.com/crane-hiromu/PadOSDC_Japan_App PadOSDC.swiftpm
```

でcloneするように追記しておきます！
（もしくはリポジトリ名に.swiftpmを入れてもいいかも）

**Comment by crane-hiromu** [comment]
ありがとうございます🙏
