### ISSUE TITLE
ダークモードにしても再起動すると解除されてしまう

### ISSUE THREAD

**Issue by crane-hiromu** [crane-hiromu/PadOSDC_Japan_App#17]
要調査中

**Comment by noppefoxwolf** [comment]
再現手順あれば自分の方でも調査します！

一応アプリ再起動&OS再起動でも特に問題なさそうでした
iOS15.6 iPhone13mini debugビルド

**Comment by crane-hiromu** [comment]
動画貼っておきます🙏

iPhone mini 15.4
OSによって動作が変わってしまうんですかね🤔

https://user-images.githubusercontent.com/24838521/184824906-7e5461be-9675-4b01-ba8a-8314a9a5b8a3.mov
