### ISSUE TITLE
SwiftGenの導入

### ISSUE THREAD

**Issue by crane-hiromu** [crane-hiromu/PadOSDC_Japan_App#23]
ローカライズ対応に伴い、直書きのキーを置き換える

**Comment by noppefoxwolf** [comment]
PlaygroundでSwiftGenのコード生成するの大変そうなので手書きのクラスでも良いかなぁって思いました

**Comment by crane-hiromu** [comment]
メモ

物は試しでやってみたものの、すんなりはいかなそう
SPMでの導入はプラグインがないと大変そう
https://qiita.com/usamik26/items/1c2cec0903fea2e03344
