### ISSUE TITLE
ライセンスの導入

### ISSUE THREAD

**Issue by crane-hiromu** [crane-hiromu/PadOSDC_Japan_App#30]
https://github.com/cybozu/LicenseList

**Comment by crane-hiromu** [comment]
> Add Run Script to the Build Phase of the Target.

Run Script が動作するのか不明なため無理かもしれない。。。

一応、手動で生成して入れ込めば画面は作れるので、github actionsで master merge 度に動かすみたいな方法も検討する

**Comment by uhooi** [comment]
ライセンスは頻繁に変わるものではないから、ワイは Run Script でなく CI で生成していいと思う！
ウホーイ図鑑はそうしていて、生成物のコミットはしていない↓
https://github.com/uhooi/UhooiPicBook/blob/d5fdfc023a1bf502090029dbb47cf8b6ccaa7de0/.github/workflows/templates/setup-ios/action.yml#L37-L40

**Comment by crane-hiromu** [comment]
Swift5.6で使える SPMの build tool が面白そうかなと思ったけど、時間があればやろうかなと言う温度感で、一旦はmakeで実行することにした笑

**Comment by uhooi** [comment]
一旦はそれでいいと思う笑

**Comment by crane-hiromu** [comment]
メモ
https://github.com/mui-z/SwiftCLIToolTemplate

**Comment by crane-hiromu** [comment]
動作を確認

https://developer.apple.com/documentation/xcode/bundling-resources-with-a-swift-package
