### ISSUE TITLE
Swift Playgroundsで開こうとするとクラッシュする

### ISSUE THREAD

**Issue by uhooi** [crane-hiromu/PadOSDC_Japan_App#46]
表題の通り。

---

__環境__

- PC: MacBook Pro（14インチ、2021）
- チップ: Apple M1 Pro
- OS: macOS Monterey 12.5.1

**Comment by crane-hiromu** [comment]
https://twitter.com/hcrane14/status/1566250884795105280

常に起こらないようにしないとまずそうだが、ツールのバグの可能性もある

**Comment by crane-hiromu** [comment]
ちなみにSPMのライブラリって手動（コマンドライン実行）で手元に落とせないんだっけ🤔
できるなら、初回だけそれやってもらうみたいなフローにしたいな。。

**Comment by uhooi** [comment]
Xcode で開いて SPM で管理しているライブラリを fetch したら、クラッシュせずに開けるようになったー！

**Comment by uhooi** [comment]
`swift package` コマンドでいけたような気がする 🤔
