### ISSUE TITLE
CLIを導入するとビルドできなくなるので調査

### ISSUE THREAD

**Issue by crane-hiromu** [crane-hiromu/PadOSDC_Japan_App#48]
https://github.com/crane-hiromu/PadOSDC_Japan_App/pull/40
https://github.com/crane-hiromu/PadOSDC_Japan_App/pull/47

一旦revertした🙏

**Comment by crane-hiromu** [comment]
マルチターゲットできないのでそれが原因かも？

**Comment by crane-hiromu** [comment]
@uhooi

**Comment by uhooi** [comment]
むむ
どんなエラーが出る？

**Comment by crane-hiromu** [comment]
`import PackageDescription` が no such file と言われちゃう感じだったな（今再現できないので🙏）

あと、ディレクトリーのツリーにもファイルが見当たらなかったから、これも関係ある...?

**Comment by uhooi** [comment]
あ、それオレも出て諦めていた、、
思ったのが、 `.swiftpm` をルートにするのでなく直下に置いて、 `Makefile` や `Tools` などを外に出して並列にするのはどうだろ？

**Comment by crane-hiromu** [comment]
> .swiftpm をルートにするのでなく直下に置いて

playgrounds を git で管理する都合上それは多分できないんよな...（やってみて貰えばわかる）

**Comment by uhooi** [comment]
まじかぁ…。
何でできないんだろ？ 試してみるー

**Comment by uhooi** [comment]
あれ、普通にできた気がする

**Comment by crane-hiromu** [comment]
PR おねおね 🥺
